### ISSUE TITLE
Node Sass

### ISSUE THREAD

**Issue by amandavilela** [Webschool-io/CSS-processadores#1]
Já que os hangouts são para o pessoal do BeMean, pensei passar Sass usando node sass, pulando a parte do Sass como gem do ruby (talvez só comentar na introdução). O que acham?

Aproveitando esse gatilho e o hangout de Gulp que vai acontecer, penso em adicionar no fim da ementa a criação de tasks no Gulp para gerar o css através do scss.

**Comment by suissa** [comment]
Isso node-sass
